import { 
  AnalysisRecord, 
  AuditEvent, 
  DatabaseSchemaTable, 
  DemoScenario 
} from "./types";
import { calculateDeterministicRisk } from "./riskEngine";

export const DEMO_SCHEMA_TABLES: DatabaseSchemaTable[] = [
  {
    name: "users",
    rowCount: 50000,
    description: "Core SaaS accounts and authentication identity",
    columns: [
      { name: "id", type: "UUID", isPrimary: true },
      { name: "name", type: "VARCHAR(255)" },
      { name: "email", type: "VARCHAR(255)" },
      { name: "status", type: "VARCHAR(50)" },
      { name: "last_login", type: "TIMESTAMPTZ" },
      { name: "created_at", type: "TIMESTAMPTZ" },
      { name: "deleted_at", type: "TIMESTAMPTZ" },
    ],
    foreignKeys: [],
  },
  {
    name: "subscriptions",
    rowCount: 15000,
    description: "Active and recurring customer billing plans",
    columns: [
      { name: "id", type: "UUID", isPrimary: true },
      { name: "user_id", type: "UUID", isForeign: true, foreignTo: "users.id" },
      { name: "status", type: "VARCHAR(50)" },
      { name: "monthly_price", type: "NUMERIC(10,2)" },
      { name: "started_at", type: "TIMESTAMPTZ" },
    ],
    foreignKeys: [
      {
        sourceTable: "subscriptions",
        sourceColumn: "user_id",
        targetTable: "users",
        targetColumn: "id",
        cascadeAction: "CASCADE",
        description: "Deleting user removes active billing subscriptions automatically",
      },
    ],
  },
  {
    name: "orders",
    rowCount: 100000,
    description: "Historical transactions, checkouts, and digital goods orders",
    columns: [
      { name: "id", type: "UUID", isPrimary: true },
      { name: "user_id", type: "UUID", isForeign: true, foreignTo: "users.id" },
      { name: "amount", type: "NUMERIC(10,2)" },
      { name: "status", type: "VARCHAR(50)" },
      { name: "created_at", type: "TIMESTAMPTZ" },
    ],
    foreignKeys: [
      {
        sourceTable: "orders",
        sourceColumn: "user_id",
        targetTable: "users",
        targetColumn: "id",
        cascadeAction: "CASCADE",
        description: "Deleting user cascades deletion to all order history",
      },
    ],
  },
  {
    name: "payments",
    rowCount: 90000,
    description: "Stripe and credit card settled payment transactions",
    columns: [
      { name: "id", type: "UUID", isPrimary: true },
      { name: "order_id", type: "UUID", isForeign: true, foreignTo: "orders.id" },
      { name: "amount", type: "NUMERIC(10,2)" },
      { name: "status", type: "VARCHAR(50)" },
    ],
    foreignKeys: [
      {
        sourceTable: "payments",
        sourceColumn: "order_id",
        targetTable: "orders",
        targetColumn: "id",
        cascadeAction: "CASCADE",
        description: "Deleting order cascades deletion to payment audit records (Level 2)",
      },
    ],
  },
  {
    name: "invoices",
    rowCount: 30000,
    description: "Tax invoices and accounting compliance records",
    columns: [
      { name: "id", type: "UUID", isPrimary: true },
      { name: "user_id", type: "UUID", isForeign: true, foreignTo: "users.id" },
      { name: "amount", type: "NUMERIC(10,2)" },
      { name: "status", type: "VARCHAR(50)" },
    ],
    foreignKeys: [
      {
        sourceTable: "invoices",
        sourceColumn: "user_id",
        targetTable: "users",
        targetColumn: "id",
        cascadeAction: "RESTRICT",
        description: "Foreign key RESTRICT protects legal accounting invoices",
      },
    ],
  },
  {
    name: "sessions",
    rowCount: 120000,
    description: "Active web tokens, session caches, and device logins",
    columns: [
      { name: "id", type: "UUID", isPrimary: true },
      { name: "user_id", type: "UUID", isForeign: true, foreignTo: "users.id" },
      { name: "last_active", type: "TIMESTAMPTZ" },
    ],
    foreignKeys: [
      {
        sourceTable: "sessions",
        sourceColumn: "user_id",
        targetTable: "users",
        targetColumn: "id",
        cascadeAction: "CASCADE",
        description: "Deleting user removes web session states",
      },
    ],
  },
];

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: "inactive_users_delete",
    title: "Delete Inactive Customers (>2 Yrs)",
    description: "Agent intends to hard-delete legacy users, triggering hidden cascade across orders, payments, and 347 paying subscriptions.",
    badge: "PRIMARY DEMO",
    prompt: "Delete all customers inactive for more than two years to clean up storage.",
    sql: "DELETE FROM users WHERE last_login < NOW() - INTERVAL '2 years';",
    operation: "DELETE",
    targetTable: "users",
    expectedRiskLevel: "CRITICAL",
    expectedRiskScore: 91,
    highlightColor: "#ef4444",
    saferSql: "UPDATE users SET deleted_at = NOW() WHERE last_login < NOW() - INTERVAL '2 years';",
  },
  {
    id: "truncate_sessions",
    title: "Purge All User Sessions",
    description: "Agent attempts to truncate sessions table during maintenance, instantly logging out all 120,000 active users.",
    badge: "HIGH IMPACT",
    prompt: "Clear the active web session cache to resolve token desync issues.",
    sql: "TRUNCATE TABLE sessions;",
    operation: "TRUNCATE",
    targetTable: "sessions",
    expectedRiskLevel: "CRITICAL",
    expectedRiskScore: 77,
    highlightColor: "#f97316",
    saferSql: "DELETE FROM sessions WHERE last_active < NOW() - INTERVAL '30 days';",
  },
  {
    id: "update_missing_where",
    title: "Cancel Subscriptions (No WHERE)",
    description: "Agent hallucinates SQL missing a WHERE predicate, accidentally canceling all 15,000 active customer subscriptions.",
    badge: "DISASTER PREVENTED",
    prompt: "Cancel trial subscriptions that expired last month.",
    sql: "UPDATE subscriptions SET status = 'cancelled';",
    operation: "UPDATE",
    targetTable: "subscriptions",
    expectedRiskLevel: "HIGH",
    expectedRiskScore: 66,
    highlightColor: "#ef4444",
    saferSql: "UPDATE subscriptions SET status = 'cancelled' WHERE status = 'trial' AND started_at < NOW() - INTERVAL '30 days';",
  },
  {
    id: "drop_invoices",
    title: "Drop Invoices Table",
    description: "Agent attempts to drop what it believes is a temporary invoices table, threatening financial audit compliance.",
    badge: "CRITICAL DANGER",
    prompt: "Drop the old invoices table before the new billing migration.",
    sql: "DROP TABLE invoices;",
    operation: "DROP",
    targetTable: "invoices",
    expectedRiskLevel: "HIGH",
    expectedRiskScore: 58,
    highlightColor: "#ef4444",
    saferSql: "ALTER TABLE invoices RENAME TO invoices_backup_2026;",
  },
  {
    id: "safe_analytics_select",
    title: "Safe Analytics Query",
    description: "Agent queries breakdown of users by status. Safe read-only execution passes directly without review blocks.",
    badge: "SAFE QUERY",
    prompt: "Show me user distribution counts grouped by status.",
    sql: "SELECT status, COUNT(*) as user_count FROM users GROUP BY status ORDER BY user_count DESC;",
    operation: "SELECT",
    targetTable: "users",
    expectedRiskLevel: "LOW",
    expectedRiskScore: 0,
    highlightColor: "#10b981",
    saferSql: "SELECT status, COUNT(*) as user_count FROM users GROUP BY status ORDER BY user_count DESC;",
  },
];

export function getInitialPrimaryAnalysis(): AnalysisRecord {
  const riskBreakdown = calculateDeterministicRisk({
    operation: "DELETE",
    directRows: 12481,
    totalRowsInTable: 50000,
    cascadeTablesCount: 3,
    cascadedRows: 49233,
    activePayingUsers: 347,
    isHardDelete: true,
    hasWhereClause: true,
  });

  return {
    id: "ANL-8821-SAAS",
    sessionId: "SES-TRUEFORGE-092",
    timestamp: "2026-08-27T22:00:15Z",
    prompt: "Delete inactive customers older than 2 years",
    originalSql: "DELETE FROM users\nWHERE last_login < NOW() - INTERVAL '2 years';",
    operationType: "DELETE",
    targetTable: "users",
    condition: "last_login < NOW() - INTERVAL '2 years'",
    status: "WAITING_APPROVAL",
    
    riskScore: riskBreakdown.totalScore,
    riskLevel: "CRITICAL",
    riskBreakdown,
    
    directRows: 12481,
    indirectRows: 49233,
    totalAffectedRows: 61714,
    cascadesCount: 3,
    
    businessImpact: {
      activePayingUsers: 347,
      mrrAtRisk: 6116,
      arrAtRisk: 73392,
      criticalTablesAffected: ["subscriptions", "orders", "payments"],
      summary: "347 paying customers with active billing plans will have their accounts and subscriptions deleted, resulting in $73.4K ARR immediate revenue destruction.",
    },
    
    tableDiffs: [
      {
        tableName: "users",
        beforeCount: 50000,
        afterCount: 37519,
        delta: -12481,
        action: "DELETE",
        cascadeType: "DIRECT",
        description: "Direct target: Inactive users matching WHERE condition",
      },
      {
        tableName: "orders",
        beforeCount: 100000,
        afterCount: 78997,
        delta: -21003,
        action: "DELETE",
        cascadeType: "CASCADE",
        description: "ON DELETE CASCADE from users.id → orders.user_id",
      },
      {
        tableName: "payments",
        beforeCount: 90000,
        afterCount: 71799,
        delta: -18201,
        action: "DELETE",
        cascadeType: "CASCADE",
        description: "ON DELETE CASCADE level 2 from orders.id → payments.order_id",
      },
      {
        tableName: "subscriptions",
        beforeCount: 15000,
        afterCount: 14653,
        delta: -347,
        action: "DELETE",
        cascadeType: "CASCADE",
        description: "ON DELETE CASCADE from users.id → subscriptions.user_id (347 active!)",
      },
      {
        tableName: "sessions",
        beforeCount: 120000,
        afterCount: 110318,
        delta: -9682,
        action: "DELETE",
        cascadeType: "CASCADE",
        description: "ON DELETE CASCADE from users.id → sessions.user_id",
      },
      {
        tableName: "invoices",
        beforeCount: 30000,
        afterCount: 30000,
        delta: 0,
        action: "NONE",
        cascadeType: "RESTRICT",
        description: "Protected: Foreign key RESTRICT prevents direct row destruction",
      },
    ],
    
    recommendedAlternative: {
      title: "Soft Delete via deleted_at Timestamp",
      sql: "UPDATE users \nSET deleted_at = NOW() \nWHERE last_login < NOW() - INTERVAL '2 years';",
      explanation: "Applies soft-delete flags without triggering cascading deletes on subscriptions, orders, or payments. Historical audit trails and billing links remain intact.",
      riskScore: 34,
      riskLevel: "MEDIUM",
      directRows: 12481,
      indirectRows: 0,
      arrAtRisk: 0,
      reversibility: "100% Recoverable (UPDATE users SET deleted_at = NULL)",
      benefits: [
        "Zero cascading deletions across orders, payments, and subscriptions",
        "$0.00 ARR revenue exposure preserved",
        "Full point-in-time reversibility without requiring database restore",
        "Compliant with data retention and billing audit regulations",
      ],
    },
    
    isUsingSaferAlternative: false,
    
    steps: [
      {
        id: "step_intercept",
        title: "Action Intercepted",
        subtitle: "TrueForge MCP Gateway trapped destructive statement",
        status: "completed",
        timestamp: "22:00:15.102",
        details: "Destructive query detected: DELETE on table `users`",
      },
      {
        id: "step_parse",
        title: "SQL AST Parsed",
        subtitle: "sqlglot extracted target, dialect, and WHERE filter",
        status: "completed",
        timestamp: "22:00:15.148",
        details: "Target table: users | Predicate: last_login < NOW() - INTERVAL '2 years'",
      },
      {
        id: "step_schema",
        title: "Production Schema Inspected",
        subtitle: "Loaded 5 foreign key constraints and cascade rules",
        status: "completed",
        timestamp: "22:00:15.210",
        details: "Found 4 ON DELETE CASCADE dependencies and 1 RESTRICT rule",
      },
      {
        id: "step_sandbox",
        title: "Isolated Sandbox Snapshot Restored",
        subtitle: "Warmed sandbox container initialized to 100% replica",
        status: "completed",
        timestamp: "22:00:15.340",
        details: "Restored snapshot `blastshield_prod_snap_latest` (50,000 users)",
      },
      {
        id: "step_simulate",
        title: "Safe Simulation Executed",
        subtitle: "Measured exact row count deltas across all tables",
        status: "completed",
        timestamp: "22:00:15.520",
        details: "Direct impact: 12,481 rows deleted | Total cascaded: 49,233 rows",
      },
      {
        id: "step_dependency",
        title: "Dependency Graph Traced (2 Levels)",
        subtitle: "Discovered cascading deletion paths to orders & payments",
        status: "completed",
        timestamp: "22:00:15.610",
        details: "users → orders (21,003) → payments (18,201) | users → subscriptions (347)",
      },
      {
        id: "step_business",
        title: "Business Impact & ARR Loss Computed",
        subtitle: "Identified paying customers and financial exposure",
        status: "completed",
        timestamp: "22:00:15.705",
        details: "347 active paying subscriptions in blast radius = $73,392 ARR at risk",
      },
      {
        id: "step_alternative",
        title: "Safer Alternative Synthesized",
        subtitle: "Soft-delete UPDATE generated with risk drop 91 → 34",
        status: "completed",
        timestamp: "22:00:15.820",
        details: "Recommended: UPDATE users SET deleted_at = NOW()",
      },
    ],
  };
}

export function generateAnalysisForScenario(scenario: DemoScenario): AnalysisRecord {
  if (scenario.id === "inactive_users_delete") {
    return getInitialPrimaryAnalysis();
  }

  if (scenario.id === "truncate_sessions") {
    const risk = calculateDeterministicRisk({
      operation: "TRUNCATE",
      directRows: 120000,
      totalRowsInTable: 120000,
      cascadeTablesCount: 0,
      cascadedRows: 0,
      activePayingUsers: 0,
      isHardDelete: true,
      hasWhereClause: false,
    });

    return {
      id: "ANL-9402-SESS",
      sessionId: "SES-TRUEFORGE-092",
      timestamp: new Date().toISOString(),
      prompt: scenario.prompt,
      originalSql: scenario.sql,
      operationType: "TRUNCATE",
      targetTable: "sessions",
      condition: "NONE (Unconditional Truncate)",
      status: "WAITING_APPROVAL",
      riskScore: risk.totalScore,
      riskLevel: risk.level,
      riskBreakdown: risk,
      directRows: 120000,
      indirectRows: 0,
      totalAffectedRows: 120000,
      cascadesCount: 0,
      businessImpact: {
        activePayingUsers: 14653,
        mrrAtRisk: 0,
        arrAtRisk: 0,
        criticalTablesAffected: ["sessions"],
        summary: "120,000 active web sessions will be wiped, immediately terminating active sessions for all logged-in users including paying subscribers.",
      },
      tableDiffs: [
        {
          tableName: "sessions",
          beforeCount: 120000,
          afterCount: 0,
          delta: -120000,
          action: "TRUNCATE",
          cascadeType: "DIRECT",
          description: "All rows immediately deleted",
        },
      ],
      recommendedAlternative: {
        title: "Targeted Inactive Session Purge",
        sql: scenario.saferSql,
        explanation: "Purges only stale sessions inactive for 30+ days while keeping active user tokens alive.",
        riskScore: 22,
        riskLevel: "LOW",
        directRows: 18450,
        indirectRows: 0,
        arrAtRisk: 0,
        reversibility: "Stale session purge is normal maintenance",
        benefits: ["Preserves all active user logins", "Zero disruption to paying subscribers"],
      },
      isUsingSaferAlternative: false,
      steps: [
        { id: "1", title: "Action Intercepted", subtitle: "TRUNCATE caught on sessions", status: "completed" },
        { id: "2", title: "SQL AST Parsed", subtitle: "TRUNCATE detected (High severity)", status: "completed" },
        { id: "3", title: "Sandbox Simulation", subtitle: "Measured 120,000 sessions dropped", status: "completed" },
        { id: "4", title: "Safer SQL Generated", subtitle: "Added 30-day age limit filter", status: "completed" },
      ],
    };
  }

  if (scenario.id === "update_missing_where") {
    const risk = calculateDeterministicRisk({
      operation: "UPDATE",
      directRows: 15000,
      totalRowsInTable: 15000,
      cascadeTablesCount: 0,
      cascadedRows: 0,
      activePayingUsers: 14653,
      isHardDelete: false,
      hasWhereClause: false,
    });

    return {
      id: "ANL-9811-SUB",
      sessionId: "SES-TRUEFORGE-092",
      timestamp: new Date().toISOString(),
      prompt: scenario.prompt,
      originalSql: scenario.sql,
      operationType: "UPDATE",
      targetTable: "subscriptions",
      condition: "NONE (Missing WHERE clause!)",
      status: "WAITING_APPROVAL",
      riskScore: risk.totalScore,
      riskLevel: risk.level,
      riskBreakdown: risk,
      directRows: 15000,
      indirectRows: 0,
      totalAffectedRows: 15000,
      cascadesCount: 0,
      businessImpact: {
        activePayingUsers: 14653,
        mrrAtRisk: 258000,
        arrAtRisk: 3096000,
        criticalTablesAffected: ["subscriptions"],
        summary: "A missing WHERE clause will cancel all 15,000 subscriptions, destroying $3.1M in annual recurring revenue.",
      },
      tableDiffs: [
        {
          tableName: "subscriptions",
          beforeCount: 15000,
          afterCount: 15000,
          delta: 15000,
          action: "UPDATE",
          cascadeType: "DIRECT",
          description: "All 15,000 rows mutated to status='cancelled'",
        },
      ],
      recommendedAlternative: {
        title: "Targeted Trial Expiry Cancellation",
        sql: scenario.saferSql,
        explanation: "Safely restricts cancellation only to trial accounts older than 30 days.",
        riskScore: 28,
        riskLevel: "MEDIUM",
        directRows: 347,
        indirectRows: 0,
        arrAtRisk: 0,
        reversibility: "Soft status update with specific WHERE filter",
        benefits: ["Shields 14,653 active paying accounts", "$3.1M ARR revenue safeguarded"],
      },
      isUsingSaferAlternative: false,
      steps: [
        { id: "1", title: "Action Intercepted", subtitle: "Unbounded UPDATE caught", status: "completed" },
        { id: "2", title: "SQL AST Parsed", subtitle: "Missing WHERE clause detected", status: "completed" },
        { id: "3", title: "Business Impact Analyzed", subtitle: "14,653 paying accounts threatened", status: "completed" },
        { id: "4", title: "Safer Alternative Synthesized", subtitle: "WHERE predicate applied", status: "completed" },
      ],
    };
  }

  if (scenario.id === "drop_invoices") {
    const risk = calculateDeterministicRisk({
      operation: "DROP",
      directRows: 30000,
      totalRowsInTable: 30000,
      cascadeTablesCount: 0,
      cascadedRows: 0,
      activePayingUsers: 14653,
      isHardDelete: true,
      hasWhereClause: false,
    });

    return {
      id: "ANL-9926-INV",
      sessionId: "SES-TRUEFORGE-092",
      timestamp: new Date().toISOString(),
      prompt: scenario.prompt,
      originalSql: scenario.sql,
      operationType: "DROP",
      targetTable: "invoices",
      condition: "DDL schema mutation (entire table)",
      status: "WAITING_APPROVAL",
      riskScore: risk.totalScore,
      riskLevel: risk.level,
      riskBreakdown: risk,
      directRows: 30000,
      indirectRows: 0,
      totalAffectedRows: 30000,
      cascadesCount: 0,
      businessImpact: {
        activePayingUsers: 0,
        mrrAtRisk: 0,
        arrAtRisk: 0,
        criticalTablesAffected: ["invoices"],
        summary: "Dropping invoices permanently removes 30,000 tax and accounting records, creating material audit, retention, and compliance exposure.",
      },
      tableDiffs: [
        {
          tableName: "invoices",
          beforeCount: 30000,
          afterCount: 0,
          delta: -30000,
          action: "DROP",
          cascadeType: "DIRECT",
          description: "Entire invoices table and its schema would be removed",
        },
      ],
      recommendedAlternative: {
        title: "Quarantine via Table Rename",
        sql: scenario.saferSql,
        explanation: "Renames the legacy table so the migration can proceed while preserving every invoice and its schema for audit or rollback.",
        riskScore: 19,
        riskLevel: "LOW",
        directRows: 0,
        indirectRows: 0,
        arrAtRisk: 0,
        reversibility: "Instantly reversible with a second ALTER TABLE RENAME",
        benefits: [
          "Preserves all 30,000 financial records",
          "Maintains the complete table schema for rollback",
          "Avoids an irreversible DDL operation",
        ],
      },
      isUsingSaferAlternative: false,
      steps: [
        { id: "1", title: "Action Intercepted", subtitle: "DROP TABLE caught at the production gateway", status: "completed" },
        { id: "2", title: "DDL Intent Parsed", subtitle: "Full schema destruction detected", status: "completed" },
        { id: "3", title: "Retention Policy Matched", subtitle: "Invoices classified as protected financial records", status: "completed" },
        { id: "4", title: "Sandbox Simulation", subtitle: "30,000 records and table definition removed", status: "completed" },
        { id: "5", title: "Reversible Plan Synthesized", subtitle: "Quarantine rename generated instead of DROP", status: "completed" },
      ],
    };
  }

  // Fallback / Safe select
  return {
    id: "ANL-0012-SAFE",
    sessionId: "SES-TRUEFORGE-092",
    timestamp: new Date().toISOString(),
    prompt: scenario.prompt,
    originalSql: scenario.sql,
    operationType: scenario.operation,
    targetTable: scenario.targetTable,
    condition: "N/A",
    status: "APPROVED",
    riskScore: 0,
    riskLevel: "LOW",
    riskBreakdown: calculateDeterministicRisk({
      operation: "SELECT",
      directRows: 0,
      totalRowsInTable: 50000,
      cascadeTablesCount: 0,
      cascadedRows: 0,
      activePayingUsers: 0,
      isHardDelete: false,
      hasWhereClause: true,
    }),
    directRows: 0,
    indirectRows: 0,
    totalAffectedRows: 0,
    cascadesCount: 0,
    businessImpact: {
      activePayingUsers: 0,
      mrrAtRisk: 0,
      arrAtRisk: 0,
      criticalTablesAffected: [],
      summary: "Safe read query with zero state modification.",
    },
    tableDiffs: [],
    recommendedAlternative: {
      title: "Identical Query (Already Safe)",
      sql: scenario.sql,
      explanation: "SELECT queries have 0 blast radius.",
      riskScore: 0,
      riskLevel: "LOW",
      directRows: 0,
      indirectRows: 0,
      arrAtRisk: 0,
      reversibility: "Non-mutating read query",
      benefits: ["Immediate execution without risk gating"],
    },
    isUsingSaferAlternative: false,
    steps: [
      { id: "1", title: "Action Intercepted", subtitle: "SELECT operation verified", status: "completed" },
      { id: "2", title: "Risk Score Computed", subtitle: "0 / 100 Risk Score (SAFE)", status: "completed" },
    ],
  };
}

export const INITIAL_AUDIT_EVENTS: AuditEvent[] = [
  {
    id: "EVT-9921",
    analysisId: "ANL-8821-SAAS",
    eventType: "ACTION_INTERCEPTED",
    description: "TrueForge agent intercepted DELETE query targeting table `users`",
    actor: "TrueForge Gateway (agent-db-operator)",
    createdAt: "2026-08-27T22:00:15.102Z",
    payload: {
      query: "DELETE FROM users WHERE last_login < NOW() - INTERVAL '2 years';",
      ip: "10.0.4.12",
      harness: "BlastShield-MCP-v1",
    },
  },
  {
    id: "EVT-9922",
    analysisId: "ANL-8821-SAAS",
    eventType: "SANDBOX_CREATED",
    description: "Postgres isolated sandbox `blastshield_sandbox` restored from clean production snapshot",
    actor: "BlastShield Sandbox Manager",
    createdAt: "2026-08-27T22:00:15.340Z",
    payload: {
      snapshot_id: "snap-prod-20260827-clean",
      duration_ms: 138,
      tables_restored: 6,
    },
  },
  {
    id: "EVT-9923",
    analysisId: "ANL-8821-SAAS",
    eventType: "SIMULATION_COMPLETED",
    description: "Sandbox dry-run measured 12,481 direct and 49,233 indirect cascaded row deletions",
    actor: "BlastShield Impact Engine",
    createdAt: "2026-08-27T22:00:15.520Z",
    payload: {
      direct_rows: 12481,
      indirect_rows: 49233,
      total_rows: 61714,
      cascades: ["orders", "payments", "subscriptions", "sessions"],
    },
  },
  {
    id: "EVT-9924",
    analysisId: "ANL-8821-SAAS",
    eventType: "RISK_CALCULATED",
    description: "Deterministic risk engine scored operation 91/100 (CRITICAL) with $73,392 ARR at risk",
    actor: "BlastShield Risk Engine",
    createdAt: "2026-08-27T22:00:15.705Z",
    payload: {
      score: 91,
      level: "CRITICAL",
      paying_users_impacted: 347,
      arr_at_risk: 73392,
    },
  },
];
